name: Build MAX Antivirus
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build EXE
        run: |
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release --target MAX
      - name: Upload Final Version
        uses: actions/upload-artifact@v4
        with:
          name: MAX_Antivirus_Ready
          path: |
            build/Release/MAX.exe
            build/_deps/webview2-src/build/native/x64/WebView2Loader.dll
